name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: "aditya-khote-140" # Your GitHub username
          outputs: |
            dist/github-snake.svg

      - name: Upload Snake
        uses: actions/upload-artifact@v2
        with:
          name: github-snake
          path: dist/github-snake.svg
